create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  team_name text not null unique,
  current_stage integer not null default 1,
  answers jsonb not null default '{}'::jsonb,
  score integer not null default 0,
  finished boolean not null default false,
  updated_at timestamptz not null default now()
);

alter table public.teams enable row level security;

-- MVP policies for a public quiz app hosted on GitHub Pages.
-- These are intentionally simple so the demo works quickly.
-- Important: anyone with the public frontend can technically read/write this table
-- unless you replace this with the secure architecture described in the README.

drop policy if exists "public read teams" on public.teams;
create policy "public read teams"
  on public.teams
  for select
  to anon
  using (true);

drop policy if exists "public insert teams" on public.teams;
create policy "public insert teams"
  on public.teams
  for insert
  to anon
  with check (true);

drop policy if exists "public update teams" on public.teams;
create policy "public update teams"
  on public.teams
  for update
  to anon
  using (true)
  with check (true);
